authors:
  yukai:
    name: Yukai
    description: The person who tried to glue ideas and tech together. 
    avatar: http://jing.games/blog/assets/image/yukai.jpg
  loomi:
    name: Loomi
    description: The person who wants to transfer feelings through visuals.
    avatar: http://jing.games/blog/assets/image/loomi_avatar.jpg
    url: https://x.com/loomilon