authors:
  yukai:
    name: 矩阵
    description: 一个想把奇想和技术黏在一起的人。 
    avatar: http://jing.games/assets/avatars/yukai_avatar.jpg
  loomi:
    name: 卢米
    description: 一个想用视觉传递感受的人。
    avatar: http://jing.games/assets/avatars/loomi_avatar.jpg
    url: https://x.com/loomilon