site_name: JING GAMES
site_url: https://jing.games/zh

theme:
  name: material
  custom_dir: overrides
  language: en
  font:
    text: Neuton # Set Neuton as the main text font
    code: Roboto Mono # For code blocks
  features:
    - navigation.path
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.indexes 
    - search.suggest
    - content.tooltips
    - navigation.tabs          # Enables navigation tabs at the top
    - navigation.tabs.sticky  # Optional: Keeps tabs fixed at the top when scrolling
    - navigation.language_selector  # Enables language switcher
    - content.code.copy
    - content.tabs
docs_dir: docs
site_dir: site

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - tags
  - blog:
      blog_dir: blog
      post_dir: "blog/posts"
      post_excerpt: optional
      pagination: true
      posts_per_page: 5
  # - macros:
  #     module_name: main

extra:
  alternate:
    - name: English
      link: https://jing.games/
      lang: en
  blog_posts:
    - title: 第一篇日志
      url: blog/2025/07/30/第一篇日志/
      excerpt: 亲爱的开发日志,我们是矩阵和卢米，一对花了数年时间开发我们的游戏《异路浮生》的夫妇。这是给你的第一封日志，也是一封迟到了很久的日志。我们知道应该从一开始就写下游戏开发过程中的点点滴滴，分享我们一路走来的喜悦、挫折甚至愤怒。可是，为什么我们迟迟没有这么做呢？
      date: 2025-07-30
    - title: 破冰小文
      url: blog/posts/2025/08/06/破冰小文/
      excerpt: 在敲击接下来的文字之前，我需要先热热身。距离上一次认真投入地写文章，已经是好多年过去了。我在想，如果我是一个从来不会写东西的人，不懂怎么遣词造句，那么即便我就打出前面这一段话，看着这段话呈现在网络上的那一瞬间，我都会高兴地手舞足蹈了。
      date: 2025-08-09
    - title: 叙事沙盒游戏
      url: blog/posts/2025/08/16/叙事沙盒游戏/
      excerpt: 我们正在开发的游戏《Indulgence》是一款叙事沙盒游戏（Narrative Sandbox Game）。与ACT、RPG或Rogue-lite这些流玩家的更熟悉游戏不同，叙事沙盒游戏的玩家群体偏核心向，主流玩家对它并不是不熟悉。所以我认为在讨论我们自己的游戏之前，有必要先介绍一下叙事沙盒游戏这个类型。
      date: 2025-08-16

nav:
  - Home: index.md
  - Blog: 
    - blog/index.md

extra_css:
  - stylesheets/extra.css
